### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by e271828-** [vavilon-js/vavilon.js#29]
Looks like a cool solution.

Are there any sites using this in production?

V2 seems to be in an open PR. Should we be using that, or is v1 still maintained?

From a quick look, it's not handling things like links inside of paragraphs or some other typical i18n cases.

Also, the data loading strategy should probably be changed. No one is going to load 100 JSON files when they only need 1.

Right way to do it is probably to have the user specify a `base_uri` arg for `path/<lang>.json` and `available_langs` array that the script pulls on load to choose best lang.

**Comment by kytta** [comment]
Hello! No, v2 is a WIP and definitely not a production-ready version. For now, you should use the v1. The websites that are using it are [vavilon.js.org](https://vavilon.js.org) (has [source code](https://github.com/vavilon-js/vavilon-js.github.io) on GitHub) and [karamoff.dev](https://karamoff.dev) (not open-source yet).

When it comes to links inside paragraphs, there is a hacky way around it — you can put wrap the whole text inside paragraph in `<span>`s and localize them one by one. I think you can find this hack on the vavilon website or you can check #26.

You're right about the dictionaries. I have left it this way for the initial release because I imagined this project to be primarily useful to the owners of small static websites, who usually don't have a lot of dictionaries and the dictionaries themselves are not that big. For v2 I plan to alter this behaviour, and I like your solution here.

**Comment by e271828-** [comment]
Thanks, solution I outlined is cleaner as it also lets you render immediately after fetch. 

For the moment I'm instead doing the following, since we already had `Language.getLocale()` handy. Note the ugly `setTimeout`; it doesn't appear to work reliably without that.

```js
var browser_lang = Language.getLocale();
var tr_root = 'https://<our-site>/tr/'
var tr_path = tr_root + browser_lang + '.json';

if (browser_lang !== "en") {
        // load correct lang JSON
        var element = document.createElement("script");
        element.src = tr_path;
        element.setAttribute("type", "application/json");
        element.setAttribute("data-vavilon-dict", browser_lang);
        document.body.appendChild(element);

        // load vavilon JS
        var element2 = document.createElement("script");
        element2.src = "https://<our-site>/vavilon.min.js";
        document.body.appendChild(element2);

        // no reliable translation without this
        setTimeout(function() {
            setLang(browser_lang)
        }, 750);
};
```

**Comment by kytta** [comment]
Hmm, that `setTimeout` looks weird to me. Are you sure it doesn't work without it? Vavilon should automatically switch to `browser_lang` after loading 🤔 

Also a note: make sure you consider all possible variants of dictionaries and user's locale. If `browser_lang` will equal to, for example, `de-AT` (Austrian German), but you only have the general German translation in `de.json`, it won't be loaded. This is why [I also check the first two characters only](https://github.com/vavilon-js/vavilon.js/blob/master/src/vavilon.ts#L115) — this way I can deliver at least something to a user.

**Comment by kytta** [comment]
P. S. I am very busy at university at the moment, so I can't be sure about when I'll be able to implement a better dictionary loading technique, sorry about that :/

**Comment by e271828-** [comment]
> Hmm, that `setTimeout` looks weird to me. Are you sure it doesn't work without it? Vavilon should automatically switch to `browser_lang` after loading 🤔

It's racing the DOM insert above. This was improved as below:

```
        // due to element race
        setTimeout(function() {
            // load vavilon JS
            var element2 = document.createElement("script");
            element2.src = "https://<site>/vavilon.min.js";
            document.body.appendChild(element2);
            setLang(browser_lang)
        }, 10);
```

but a reasonable native dict load is the real solution.

> Also a note: make sure you consider all possible variants of dictionaries and user's locale. If `browser_lang` will equal to, for example, `de-AT` (Austrian German), but you only have the general German translation in `de.json`, it won't be loaded. This is why [I also check the first two characters only](https://github.com/vavilon-js/vavilon.js/blob/master/src/vavilon.ts#L115) — this way I can deliver at least something to a user.

That's what `Language.getLocale()` does.

**Comment by kytta** [comment]
Hey 👋 So, a lot has happened since June. I have decided to focus on fixing smaller bug and annoyances without completely changing the API — this is why I have now postponed the v2 until better times.

I am closing this issue, since I have created separate issues regarding the problems you have mentioned:

 - #26: links and formatting inside translated text
 - #40: optimized dictionary loading

I don't know, how fast I'll be able to implement this; stay tuned for the updates in the respective issues
